In [3]:
import pandas as pd
df=pd.read_csv('Youtube02-KatyPerry.csv')
df.sample(10)

COMMENT_ID  \
236    z13qdpxqiziasxzsv234hhqoeretuhabc04   
47   z12rgdghtm3gc3j4004cizn50y3xybujalw0k   
274    z13chb0r5lndj1mz504cefmpetrryb3qvf0   
119  z13mel5zokapi1ax004cg3goburlghkwdk40k   
222  z13nujhysyf3ftvgt04ccrd4szrxcvzbvt00k   
256    z12dynswht2rujq1e22xi5dappq1vrlh504   
30     z12qvlsqppeeyt3gp04cchwaivz4f54bbho   
215    z124whipbluof3y2t23gvfmb1la2w5aw204   
253    z133x1cptruyddomf230yx1zfwqhfzoxs04   
310    z13sx5nrhq22yvste23fvnirosixy55ag04   

                                   AUTHOR                 DATE  \
236                           Merenguette  2014-10-21T04:52:03   
47                         Littleprincess  2014-08-31T21:50:57   
274                           Nerdy Peach  2014-10-29T22:44:41   
119                               Jian Li  2014-09-16T07:45:05   
222               MeSoHornyMeLuvULongTime  2014-10-18T04:58:21   
256                             ali aydın  2014-10-25T16:59:02   
30                              anne baba  2014-08-21T21:59:13   
215  Bi - Bases of Image [Musical videos]  2014-10-15T11:02:31   
253                             Hude Deni  2014-10-25T08:13:25   
310                 The Robot Green Hypno  2014-11-07T13:37:51   

                                               CONTENT  CLASS  
236  this video is great .....!!! I love this.........      0  
47                                     Perfect! &lt;3      0  
274  Hey! I'm NERDY PEACH and I'm a new youtuber an...      1  
119                    see it all, human folly right?      0  
222  This video is so racist!!! There are only anim...      0  
256                 I like you . Katy Perry 600▲60▲6▲      0  
30   http://www.ebay.com/itm/131275322914?ssPageNam...      1  
215                                  Visit my channel      1  
253  HAPPY BIRTHDAY KATY :) http://giphy.com/gifs/b...      1  
310   i like this song the video goes perfect with it      0

In [4]:
df.isnull().sum()

COMMENT_ID    0
AUTHOR        0
DATE          0
CONTENT       0
CLASS         0
dtype: int64

In [5]:
df.head()

COMMENT_ID        AUTHOR                 DATE  \
0      z12pgdhovmrktzm3i23es5d5junftft3f   lekanaVEVO1  2014-07-22T15:27:50   
1    z13yx345uxepetggz04ci5rjcxeohzlrtf4      Pyunghee  2014-07-27T01:57:16   
2  z12lsjvi3wa5x1vwh04cibeaqnzrevxajw00k    Erica Ross  2014-07-27T02:51:43   
3    z13jcjuovxbwfr0ge04cev2ipsjdfdurwck  Aviel Haimov  2014-08-01T12:27:48   
4  z13qybua2yfydzxzj04cgfpqdt2syfx53ms0k    John Bello  2014-08-01T21:04:03   

                                             CONTENT  CLASS  
0  i love this so much. AND also I Generate Free ...      1  
1  http://www.billboard.com/articles/columns/pop-...      1  
2  Hey guys! Please join me in my fight to help a...      1  
3  http://psnboss.com/?ref=2tGgp3pV6L this is the...      1  
4  Hey everyone. Watch this trailer!!!!!!!!  http...      1

In [6]:
df['CONTENT'][0]

'i love this so much. AND also I Generate Free Leads on Auto Pilot &amp; You Can  Too! http://www.MyLeaderGate.com/moretraffic\ufeff'

In [7]:
df.shape

(350, 5)

In [8]:
X=df['CONTENT']
y=df['CLASS']

X,y

(0      i love this so much. AND also I Generate Free ...
 1      http://www.billboard.com/articles/columns/pop-...
 2      Hey guys! Please join me in my fight to help a...
 3      http://psnboss.com/?ref=2tGgp3pV6L this is the...
 4      Hey everyone. Watch this trailer!!!!!!!!  http...
                              ...                        
 345    This song means so much to me thank you  soooo...
 346                                               &lt;3
 347    KATY PERRY, I AM THE "DÉCIO CABELO", "DECIO HA...
 348    Honestly speaking except taylor swift and adel...
 349    who is going to reach the billion first : katy...
 Name: CONTENT, Length: 350, dtype: object,
 0      1
 1      1
 2      1
 3      1
 4      1
       ..
 345    0
 346    0
 347    1
 348    0
 349    0
 Name: CLASS, Length: 350, dtype: int64)

In [1]:
import tensorflow as tf
tf.__version__

'2.13.0'

In [9]:
from tensorflow.keras.layers import Embedding, LSTM, Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [10]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
lem = WordNetLemmatizer()

In [17]:
# Data preprocessing
corpus=[]
for messages in X:
    review = re.sub('[^A-Za-z0-9]',' ',messages)
    review = review.lower()
    review = review.split()
    
    review = [lem.lemmatize(word) for word in review if word not in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [20]:
len(corpus)

350

In [21]:
corpus

['love much also generate free lead auto pilot amp http www myleadergate com moretraffic',
 'http www billboard com article column pop shop 6174122 fan army face round 3 vote sone please vip please help u gt lt',
 'hey guy please join fight help abused mistreated animal fund go helping pay vet bill helping find home place extra emphasis helping disabled animal one otherwise would put sleep animal organization donate please http www gofundme com angel n wingz',
 'http psnboss com ref 2tggp3pv6l song',
 'hey everyone watch trailer http believemefilm com hlr h2hqbuvb',
 'check rapping hope guy like http soundcloud com nereboy call lostproduce atlastatlas rapper jkork follow message',
 'subscribe pleaaaase instagram account subscribe back http instagram com cyrine ghorbel',
 'hey guy visit channel pleaase searching dream',
 'nice http www barnesandnoble com bdp csrftoken i9tixe8cnkcosoqkemgjlu5uwv6nsxso amp sort dd amp size 90 amp csrftoken 89iyec7nrwp5nytno5u7amhvmflutggl amp dref 5094 am

In [22]:
# importing Counter module
from collections import Counter

# creating a list with the keys
items = Counter(corpus).keys()
print("No of unique items in the corpus are:", len(items))


No of unique items in the corpus are: 345


In [28]:
words

'going reach billion first katy taylor'

In [32]:
one_hot(words,345)

[97, 115, 308, 12, 274, 250]

In [24]:
for words in corpus:
    print(words + "\n")

love much also generate free lead auto pilot amp http www myleadergate com moretraffic

http www billboard com article column pop shop 6174122 fan army face round 3 vote sone please vip please help u gt lt

hey guy please join fight help abused mistreated animal fund go helping pay vet bill helping find home place extra emphasis helping disabled animal one otherwise would put sleep animal organization donate please http www gofundme com angel n wingz

http psnboss com ref 2tggp3pv6l song

hey everyone watch trailer http believemefilm com hlr h2hqbuvb

check rapping hope guy like http soundcloud com nereboy call lostproduce atlastatlas rapper jkork follow message

subscribe pleaaaase instagram account subscribe back http instagram com cyrine ghorbel

hey guy visit channel pleaase searching dream

nice http www barnesandnoble com bdp csrftoken i9tixe8cnkcosoqkemgjlu5uwv6nsxso amp sort dd amp size 90 amp csrftoken 89iyec7nrwp5nytno5u7amhvmflutggl amp dref 5094 amp keyword bdp amp store eb

In [33]:
## One hot representation of corpus
voc_size = 345

onehot_repr = [one_hot(words,voc_size) for words in corpus]
onehot_repr

[[110, 179, 289, 182, 54, 161, 115, 182, 286, 119, 193, 275, 87, 189],
 [119,
  193,
  192,
  87,
  191,
  103,
  146,
  111,
  211,
  224,
  214,
  324,
  344,
  280,
  236,
  52,
  70,
  44,
  70,
  309,
  243,
  310,
  68],
 [26,
  140,
  70,
  138,
  128,
  309,
  28,
  256,
  139,
  41,
  343,
  150,
  296,
  241,
  32,
  150,
  96,
  121,
  319,
  191,
  85,
  150,
  142,
  139,
  284,
  95,
  220,
  198,
  174,
  139,
  283,
  265,
  70,
  119,
  193,
  34,
  87,
  331,
  68,
  241],
 [119, 303, 87, 59, 124, 299],
 [26, 31, 26, 330, 119, 42, 87, 133, 306],
 [321, 280, 43, 140, 284, 119, 18, 87, 320, 37, 34, 18, 187, 216, 98, 57],
 [301, 334, 296, 194, 301, 191, 119, 296, 87, 119, 283],
 [26, 140, 262, 165, 303, 222, 36],
 [148,
  119,
  193,
  21,
  87,
  237,
  108,
  134,
  286,
  311,
  254,
  286,
  37,
  47,
  286,
  108,
  154,
  286,
  77,
  248,
  286,
  15,
  237,
  286,
  302,
  121],
 [119, 193, 175, 326, 82],
 [26,
  140,
  35,
  183,
  62,
  226,
  165,
  70,
  343,

In [34]:
corpus[0]

'love much also generate free lead auto pilot amp http www myleadergate com moretraffic'

In [36]:
onehot_repr[0]

[110, 179, 289, 182, 54, 161, 115, 182, 286, 119, 193, 275, 87, 189]

In [59]:
for i in enumerate(lens):
    print(i)

(0, 14)
(1, 23)
(2, 40)
(3, 6)
(4, 9)
(5, 16)
(6, 11)
(7, 7)
(8, 26)
(9, 5)
(10, 26)
(11, 22)
(12, 11)
(13, 17)
(14, 9)
(15, 12)
(16, 2)
(17, 6)
(18, 2)
(19, 32)
(20, 28)
(21, 30)
(22, 61)
(23, 39)
(24, 10)
(25, 18)
(26, 12)
(27, 14)
(28, 7)
(29, 12)
(30, 14)
(31, 212)
(32, 14)
(33, 43)
(34, 43)
(35, 10)
(36, 13)
(37, 5)
(38, 15)
(39, 22)
(40, 6)
(41, 21)
(42, 8)
(43, 8)
(44, 12)
(45, 33)
(46, 7)
(47, 3)
(48, 8)
(49, 4)
(50, 28)
(51, 12)
(52, 8)
(53, 5)
(54, 9)
(55, 5)
(56, 8)
(57, 5)
(58, 2)
(59, 5)
(60, 21)
(61, 8)
(62, 5)
(63, 7)
(64, 5)
(65, 12)
(66, 5)
(67, 8)
(68, 4)
(69, 16)
(70, 3)
(71, 6)
(72, 7)
(73, 2)
(74, 11)
(75, 1)
(76, 4)
(77, 5)
(78, 2)
(79, 5)
(80, 8)
(81, 31)
(82, 35)
(83, 15)
(84, 1)
(85, 3)
(86, 17)
(87, 13)
(88, 7)
(89, 18)
(90, 4)
(91, 7)
(92, 18)
(93, 6)
(94, 4)
(95, 40)
(96, 6)
(97, 22)
(98, 2)
(99, 18)
(100, 11)
(101, 7)
(102, 1)
(103, 9)
(104, 10)
(105, 7)
(106, 4)
(107, 2)
(108, 1)
(109, 12)
(110, 32)
(111, 9)
(112, 18)
(113, 14)
(114, 8)
(115, 7)
(116, 6)
(

In [52]:
## Embedding

lens = [len(sent.split()) for sent in corpus]
sent_len = max(lens)

embedded_docs = pad_sequences(onehot_repr,padding='pre',maxlen=sent_len)
print(embedded_docs)

[[  0   0   0 ... 275  87 189]
 [  0   0   0 ... 243 310  68]
 [  0   0   0 ... 331  68 241]
 ...
 [  0   0   0 ... 179 266 205]
 [  0   0   0 ... 257  97 140]
 [  0   0   0 ...  12 274 250]]


In [60]:
embedded_docs[31]

array([ 68, 267, 310, 307, 138,  68, 237, 245,   3, 119,  16, 195,  87,
        16,  79, 111, 296, 145, 310,  79, 137, 206,  79, 286, 227, 302,
       286,  61,  32, 286,  10, 176, 286, 276, 338, 222, 286, 186, 217,
       286, 137, 344, 255, 286, 321,  29, 286, 247, 102, 286, 281,  47,
       310, 321, 299, 232, 195,  68, 310,  68, 159, 274, 157, 163, 165,
        91, 310,  44, 310,  90, 310, 241, 119,  16, 195,  87, 250,  79,
       111, 296, 145, 310,  79, 206,  79, 286, 227, 302, 286,  61,  32,
       286,  10, 176, 286, 276, 338, 222, 286, 202,  63,  20,  63,  50,
        11, 310,  68, 267, 310,  68, 224, 310,  68, 237, 245,   3, 119,
        16, 195,  87,  16,  79, 111, 296, 145, 310,  79, 137, 206,  79,
       286, 227, 302, 286,  61,  32, 286,  10, 176, 286, 276, 338, 222,
       286, 186, 217, 286, 137, 344, 255, 286, 321,  29, 286, 247, 102,
       286, 281,  47, 310, 321, 299, 232, 195,  68, 310,  68, 159, 274,
       157, 163, 165,  91, 310,  44, 310,  90, 310, 241, 119,  1

In [54]:
type(embedded_docs)

numpy.ndarray

In [56]:
## Model Creation
embedding_vector_features=20
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_len))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 212, 20)           6900      
                                                                 
 lstm_1 (LSTM)               (None, 100)               48400     
                                                                 
 dense_1 (Dense)             (None, 1)                 101       
                                                                 
Total params: 55401 (216.41 KB)
Trainable params: 55401 (216.41 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [61]:
len(embedded_docs) , y.shape

(350, (350,))

In [62]:
import numpy as np
X_final = np.array(embedded_docs)
y_final = np.array(y)

In [63]:
X_final

array([[  0,   0,   0, ..., 275,  87, 189],
       [  0,   0,   0, ..., 243, 310,  68],
       [  0,   0,   0, ..., 331,  68, 241],
       ...,
       [  0,   0,   0, ..., 179, 266, 205],
       [  0,   0,   0, ..., 257,  97, 140],
       [  0,   0,   0, ...,  12, 274, 250]])

In [64]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [65]:
## Model Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=20,batch_size=64)

Epoch 1/20
4/4 [==============================] - 10s 982ms/step - loss: 0.6914 - accuracy: 0.5513 - val_loss: 0.6885 - val_accuracy: 0.6552
Epoch 2/20
4/4 [==============================] - 2s 573ms/step - loss: 0.6839 - accuracy: 0.6197 - val_loss: 0.6801 - val_accuracy: 0.6034
Epoch 3/20
4/4 [==============================] - 2s 526ms/step - loss: 0.6729 - accuracy: 0.5812 - val_loss: 0.6679 - val_accuracy: 0.5948
Epoch 4/20
4/4 [==============================] - 2s 494ms/step - loss: 0.6496 - accuracy: 0.6496 - val_loss: 0.6532 - val_accuracy: 0.6897
Epoch 5/20
4/4 [==============================] - 2s 499ms/step - loss: 0.6195 - accuracy: 0.7222 - val_loss: 0.6289 - val_accuracy: 0.6897
Epoch 6/20
4/4 [==============================] - 2s 502ms/step - loss: 0.5914 - accuracy: 0.7137 - val_loss: 0.6079 - val_accuracy: 0.7069
Epoch 7/20
4/4 [==============================] - 2s 505ms/step - loss: 0.5559 - accuracy: 0.7949 - val_loss: 0.5987 - val_accuracy: 0.6638
Epoch 8/20
4/4 [===

## with dropout

In [68]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_len))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [69]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=100,batch_size=64)

Epoch 1/100
4/4 [==============================] - 9s 987ms/step - loss: 0.6914 - accuracy: 0.5470 - val_loss: 0.6867 - val_accuracy: 0.6724
Epoch 2/100
4/4 [==============================] - 2s 574ms/step - loss: 0.6819 - accuracy: 0.6282 - val_loss: 0.6763 - val_accuracy: 0.6466
Epoch 3/100
4/4 [==============================] - 2s 545ms/step - loss: 0.6617 - accuracy: 0.6410 - val_loss: 0.6594 - val_accuracy: 0.6034
Epoch 4/100
4/4 [==============================] - 2s 551ms/step - loss: 0.6368 - accuracy: 0.6496 - val_loss: 0.6366 - val_accuracy: 0.6897
Epoch 5/100
4/4 [==============================] - 2s 543ms/step - loss: 0.6016 - accuracy: 0.7778 - val_loss: 0.6123 - val_accuracy: 0.7241
Epoch 6/100
4/4 [==============================] - 2s 554ms/step - loss: 0.5571 - accuracy: 0.7821 - val_loss: 0.5906 - val_accuracy: 0.6983
Epoch 7/100
4/4 [==============================] - 2s 534ms/step - loss: 0.5103 - accuracy: 0.7650 - val_loss: 0.5598 - val_accuracy: 0.6983
Epoch 8/100
4

Epoch 59/100
4/4 [==============================] - 2s 521ms/step - loss: 0.0064 - accuracy: 0.9957 - val_loss: 0.3816 - val_accuracy: 0.9138
Epoch 60/100
4/4 [==============================] - 2s 525ms/step - loss: 0.0041 - accuracy: 1.0000 - val_loss: 0.4240 - val_accuracy: 0.8707
Epoch 61/100
4/4 [==============================] - 2s 538ms/step - loss: 0.0066 - accuracy: 1.0000 - val_loss: 0.4326 - val_accuracy: 0.8793
Epoch 62/100
4/4 [==============================] - 2s 545ms/step - loss: 0.0061 - accuracy: 1.0000 - val_loss: 0.4183 - val_accuracy: 0.8966
Epoch 63/100
4/4 [==============================] - 2s 534ms/step - loss: 0.0045 - accuracy: 1.0000 - val_loss: 0.3895 - val_accuracy: 0.9138
Epoch 64/100
4/4 [==============================] - 2s 530ms/step - loss: 0.0026 - accuracy: 1.0000 - val_loss: 0.3840 - val_accuracy: 0.9138
Epoch 65/100
4/4 [==============================] - 2s 545ms/step - loss: 0.0037 - accuracy: 1.0000 - val_loss: 0.4010 - val_accuracy: 0.9138
Epoch 

In [70]:
y_pred = model.predict(X_test)

4/4 [==============================] - 2s 88ms/step


In [73]:
y_pred

array([[9.6451265e-01],
       [9.9998814e-01],
       [9.9999404e-01],
       [9.7757024e-01],
       [1.0199937e-02],
       [9.9999368e-01],
       [7.3492028e-02],
       [5.4425499e-03],
       [9.9999446e-01],
       [9.9999356e-01],
       [5.4462743e-04],
       [7.2851763e-03],
       [1.3566330e-03],
       [9.1291200e-05],
       [9.9988204e-01],
       [1.2653899e-04],
       [2.1543954e-05],
       [9.9960518e-01],
       [1.0732784e-05],
       [1.9727380e-04],
       [6.0520022e-05],
       [9.9974406e-01],
       [9.9999475e-01],
       [9.9999571e-01],
       [9.9998540e-01],
       [9.9999142e-01],
       [6.6727761e-04],
       [9.9998128e-01],
       [3.6647710e-01],
       [1.8044231e-05],
       [9.8978680e-01],
       [9.9998379e-01],
       [9.9999779e-01],
       [6.6485251e-03],
       [9.9998438e-01],
       [9.9995279e-01],
       [3.9067908e-04],
       [9.9999458e-01],
       [5.0719878e-05],
       [4.1720435e-01],
       [1.0477325e-05],
       [5.952435

In [74]:
y_pred=np.where(y_pred > 0.5, 1,0) ##AUC ROC Curve

In [72]:
y_test

array([1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 1], dtype=int64)

In [76]:
from sklearn.metrics import confusion_matrix, classification_report
confusion_matrix(y_test,y_pred)

array([[50,  8],
       [ 3, 55]], dtype=int64)

In [78]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.94      0.86      0.90        58
           1       0.87      0.95      0.91        58

    accuracy                           0.91       116
   macro avg       0.91      0.91      0.90       116
weighted avg       0.91      0.91      0.90       116



In [79]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9051724137931034